use customerdb;
select * from customer;


-- Compare total revenue generated by male vs. female customers. 
select gender, sum(purchase_amount) as Revenue
from customer
group by gender;


-- Identify customers who used discounts but still spent above the average purchase amount. 
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

-- Find top 5 products with the highest average review ratings.
select item_purchased, avg(review_rating) as rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare average purchase amounts between Standard and Express shipping type
select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Subscribers vs. Non-Subscribers – Compare average spend and total revenue across subscription status. 
select subscription_status, count(*) as total_customers, avg(purchase_amount) as average_spend, sum(purchase_amount) as revenue
from customer
group by subscription_status;

-- Discount-Dependent Products – Identify 5 products with the highest percentage of discounted purchases. 
select item_purchased, round(sum(discount_applied = "Yes") * 100.0 / count(*), 2) as discounted_purchases
from customer
group by item_purchased
order by discounted_purchases desc
limit 5;

-- Customer Segmentation – Classify customers into New, Returning, and Loyal segments based on purchase history.
select customer_segment, count(*) as number_of_customers
from (
	select 
		case 
			when previous_purchases = 1 then 'New'
			when previous_purchases <= 10 then 'Returning'
			else 'Loyal'
		end as customer_segment
	from customer
    ) as t
group by customer_segment;

-- Top 3 Products per Category – List the most purchased products within each category.
select rnk, category, item_purchased, total_orders
from (
		select 
			category,
			item_purchased,
			count(item_purchased) as total_orders,
			dense_rank() over(partition by category order by count(item_purchased) desc) as rnk
		from customer
        group by category, item_purchased
	) t
where rnk <= 3;

-- Repeat Buyers & Subscriptions – Check whether customers with > 5 purchases are more likely to subscribe.
select subscription_status, count(subscription_status)
from customer
where previous_purchases > 5
group by subscription_status;

-- Revenue by Age Group – Calculate total revenue contribution of each age group
select age_group, sum(purchase_amount) as revenue
from customer
group by age_group;


